// Generated by CoffeeScript 1.7.1
(function() {
  var personal, professional;

  professional = ['Functions', 'Interfaces', 'Algorithms', 'IntelliJ IDEA', 'F#', 'Quality', 'Declarative\nprogramming', 'HTML5', 'Javascript', 'Coffeescript', 'Engineering', 'Immutability', 'Scala', 'Predictability', 'New ideas', 'Optimization', 'Node.js', 'Fixing things', 'Science', 'Protocols', 'Linux', 'Challenges', 'Progress'];

  personal = ['Games', 'RPGs', 'ZEN', 'Discovery', 'Electronic music', 'Melodic dubstep', 'Ramen', 'Dogs', 'Japan', 'Manga', 'Anime', 'Nintendo', 'Mario Bros.', 'Commodore 64', 'Nostalgia', 'Movies', 'Oldschool', 'Chillout', 'My Girlfriend'];

  module.exports = [
    {
      set: professional,
      wage: 5
    }, {
      set: personal,
      wage: 2
    }
  ];

}).call(this);

//# sourceMappingURL=sets.map
