// Generated by CoffeeScript 1.8.0
(function() {
  var typograph;

  typograph = function(node, delay) {
    var base, diff, nextWrite, resetWord, typeALetter, typeAWord, update, word, writeRecursive;
    if (delay == null) {
      delay = [50, 70];
    }
    word = '';
    nextWrite = null;
    base = delay[0];
    diff = delay[1] - delay[0];
    update = function(word) {
      return node.html(word);
    };
    typeALetter = function(letter) {
      word = "" + word + letter;
      return update(word);
    };
    resetWord = function() {
      word = '';
      return update(word);
    };
    typeAWord = function(newWord) {
      resetWord();
      clearTimeout(nextWrite);
      return writeRecursive(newWord);
    };
    writeRecursive = function(newWord) {
      if (newWord) {
        return nextWrite = setTimeout((function() {
          typeALetter(newWord.first());
          return writeRecursive(newWord.from(1));
        }), base + Math.floor(Math.random() * diff));
      }
    };
    return {
      type: typeAWord
    };
  };

  module.exports = typograph;

}).call(this);

//# sourceMappingURL=typer.js.map
